apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: busy-dm
  namespace: default
  labels:
    app: busy-dm
spec:
  template:
    metadata:
      labels:
        name: busy-dm
    spec:
      containers:
      - image: appscode/who-is-kubeadm:demo
        command:
        - annotate-kubeadm-version.sh
        imagePullPolicy: IfNotPresent
        name: busybox
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
